"""Generate 256-entry INT8→INT8 LUTs for SiLU, GELU, Sigmoid, Tanh.

Input range: signed 8-bit (-128..127) treated as x / 16 so x=16 means 1.0.
Output: signed 8-bit (-128..127) treated as y / 16 so the LUT can represent
values in roughly [-8, +8).

Run standalone to emit both the Python tables (for activation_ref.py) and
a Verilog include file (for npu_activation.v).
"""

import math
from pathlib import Path


SCALE = 16.0   # INT8 representation: value / SCALE = real


def _to_int8(x: float) -> int:
    y = round(x * SCALE)
    return max(-128, min(127, y))


def _silu(x):   # SiLU / Swish: x * sigmoid(x)
    return x * (1.0 / (1.0 + math.exp(-x)))


def _gelu(x):   # GELU approximation
    return 0.5 * x * (1 + math.erf(x / math.sqrt(2)))


def _sigmoid(x):
    return 1.0 / (1.0 + math.exp(-x))


def _tanh(x):
    return math.tanh(x)


def _build_lut(fn):
    """Return {int8_input: int8_output} for all 256 signed values."""
    out = {}
    for i in range(-128, 128):
        x_real = i / SCALE
        y_real = fn(x_real)
        out[i] = _to_int8(y_real)
    return out


def emit_verilog(path: Path):
    """Emit a Verilog include with 4 case-lookup functions."""
    lines = [
        "// Auto-generated by tools/npu_ref/gen_afu_luts.py — do not edit by hand.",
        "// 256-entry INT8->INT8 LUTs for SiLU / GELU / Sigmoid / Tanh.",
        "// Input: signed 8-bit interpreted as x/16; output likewise.",
        "",
    ]
    for name, fn in (("silu", _silu), ("gelu", _gelu),
                     ("sigmoid", _sigmoid), ("tanh", _tanh)):
        lut = _build_lut(fn)
        lines.append(f"// --- {name.upper()} LUT ---")
        lines.append(f"function automatic signed [7:0] afu_{name}_lut;")
        lines.append("    input signed [7:0] x;")
        lines.append("    begin")
        lines.append("        case (x)")
        for i in range(-128, 128):
            key = i & 0xFF
            val = lut[i] & 0xFF
            lines.append(f"            8'h{key:02X}: afu_{name}_lut = 8'h{val:02X};")
        lines.append(f"            default: afu_{name}_lut = 8'h00;")
        lines.append("        endcase")
        lines.append("    end")
        lines.append("endfunction")
        lines.append("")
    path.write_text("\n".join(lines))


def emit_python(path: Path):
    """Emit a Python module with the 4 LUTs as dicts."""
    lines = [
        '"""Auto-generated by tools/npu_ref/gen_afu_luts.py. INT8->INT8 LUTs."""',
        "",
    ]
    for name, fn in (("SILU", _silu), ("GELU", _gelu),
                     ("SIGMOID", _sigmoid), ("TANH", _tanh)):
        lut = _build_lut(fn)
        items = ", ".join(f"{i}: {lut[i]}" for i in range(-128, 128))
        lines.append(f"{name}_LUT = {{{items}}}")
        lines.append("")
    path.write_text("\n".join(lines))


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    v_path = here.parent.parent / "rtl" / "npu_activation" / "afu_luts.vh"
    py_path = here / "afu_luts.py"
    emit_verilog(v_path)
    emit_python(py_path)
    print(f"Wrote {v_path}")
    print(f"Wrote {py_path}")
    # Sanity print a few LUT values
    for name, fn in (("silu", _silu), ("gelu", _gelu),
                     ("sigmoid", _sigmoid), ("tanh", _tanh)):
        lut = _build_lut(fn)
        print(f"{name}: x=0 -> y={lut[0]}, x=16 -> y={lut[16]}, x=-32 -> y={lut[-32]}")
